branch-defaults:
  master:
    environment: CodeCh18Eb-env
    group_suffix: null
environment-defaults:
  CodeCh18Eb-env:
    branch: null
    repository: null
global:
  application_name: code-ch18-eb
  branch: null
  default_ec2_keyname: null
  default_platform: Node.js 12 running on 64bit Amazon Linux 2
  default_region: us-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
