branch-defaults:
  master:
    environment: Eecsdegree-env
    group_suffix: null
environment-defaults:
  Eecsdegree-env:
    branch: null
    repository: null
global:
  application_name: eecsdegree
  branch: null
  default_ec2_keyname: eecsdegree
  default_platform: Node.js 12 running on 64bit Amazon Linux 2
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
